### ISSUE TITLE
Update rollup

### ISSUE THREAD

**Issue by fabianwohlfart** [Miyaneee/rollup-plugin-json5#1]
Hi guys,

is it possible for you to update this package to Rollup ^4?

Thanks!

**Comment by Gu-Miao** [comment]
Hello. Is there any problem with rollup@4?

**Comment by fabianwohlfart** [comment]
Not a problem, but your package has incorrect peer dependencies:

`warning "@nuxtjs/i18n > @miyaneee/rollup-plugin-json5@1.1.2" has incorrect peer dependency "rollup@^1.20.0 || ^2.0.0 || ^3.0.0".`

**Comment by Botz** [comment]
@Gu-Miao thank you for updating the peer dependencies, any plans for an upcoming release with the updated peers?

**Comment by Gu-Miao** [comment]
v1.2.0 has been released, you could try it now
